config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"
  post 'home/add-amount', to: "home#add_amount", as: "add_amount"

  resources :your_stocks
  resources :transactions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :your_stock
end

app/models/your_amount.rb
class YourAmount < ApplicationRecord
end

app/models/your_stock.rb
class YourStock < ApplicationRecord

  has_many :transactions
  validate :check_price, :check_symbol, :check_balance

  after_save :create_transaction

  def get_current_price
    FetchDataService.new(stock_symbol).call
  end

  private
  
  def check_price
    data = FetchDataService.new(stock_symbol).call
    if buy_price.to_f < data[:current_price]
      errors.add(:buy_price, "price should be greater then current price #{data[:current_price].round(2)}")
    end
  end

  def check_symbol
    data = FetchDataService.new(stock_symbol).call
    if data[:current_price] === 0.0
      errors.add(:buy_price, "#{stock_symbol} symbol is not persent")
    end
  end

  def check_balance
    total_amount = buy_price.to_f * quatity
    account_amount = YourAmount.first.amount.to_f
    unless account_amount >= total_amount
      errors.add(:amount, "Your Balance is insufficient please add amount")
    end
  end

  def create_transaction
    amount = (self.holding ? self.sell_price.to_f : self.buy_price.to_f) * self.quatity
    self.transactions.create!(amount: amount)
    balance = YourAmount.first
    balance.update(amount: (balance.amount.to_f - amount))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @your_stocks = YourStock.where(holding: false)
  end

  def add_amount
    amount = params[:amount]
    if amount.to_f > 0
      balance = YourAmount.first
      balance.update(amount: amount.to_f+balance.amount.to_f)      
    end
    redirect_to root_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end
end

app/controllers/your_stocks_controller.rb
class YourStocksController < ApplicationController
  
  def new
    @your_stocks = YourStock.new
  end

  def create
    @your_stock = YourStock.create(your_stock_params)
    if @your_stock.errors.present?
      flash[:alert] = @your_stock.errors.messages[:buy_price][0]
    end
    redirect_to root_path
  end

  private

  def your_stock_params
    params.require(:your_stock).permit(:stock_symbol, :buy_price, :quatity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def profit(stock)
    ((stock.get_current_price[:current_price].round(2)-stock.buy_price.to_f)*stock.quatity).round(2)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/your_stock_helper.rb
module YourStockHelper
end

app/views/home/index.html.erb
<h1 class="text-center mt-3">Your Portfolio</h1>

<div class="container">
  <div class="row">
    <div class="col-lg-3 col-6">
      <h5>Your Amount</h5>
    </div>
    <div class="col-lg-3 col-6">
      <p><%= YourAmount.first.amount %></p>
    </div>
    <div class="col-lg-6 col-12">
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Add Your Amount
      </button>
  </div>
  </div>
</div>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <div class="container">
      <%= flash.alert %>
    </div>
  </div>
<% end %>

<section>
  <div class="container">
  <table class="table mt-3">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Symbol</th>
      <th scope="col">Buy Price</th>
      <th scope="col">Current Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Total Investment</th>
      <th scope="col">Profit/Loss</th>
    </tr>
  </thead>
  <tbody>
    <% @your_stocks.each do |stock|%>
    <% if stock.up_price.to_f > stock.get_current_price[:current_price].round(2) %>
      <tr class="bg-danger">
    <% elsif stock.down_price.to_f > stock.get_current_price[:current_price].round(2) %>
      <tr class="bg-success">
    <%else%>
      <tr>
    <% end %>
      <td></td>
      <td class="text-uppercase"><%= stock.stock_symbol %></td>
      <td><%= stock.buy_price %></td>
      <td><%=stock.get_current_price[:current_price].round(2)%>
      <td><%= stock.quatity %></td>
      <td><%= (stock.buy_price.to_f*stock.quatity).round(2)%>
      <td><%= profit(stock)%></td>
    </tr>
    <% end %>
  </tbody>
</table>
  </div>


</section>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Amount</h5>
      </div>
      <div class="modal-body">
        <form action="<%= add_amount_path%>" method="post">
          <input type="text" name="amount" placeholder="0.0"><br><br>
          <input type="submit" value="Submit">
        </form>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Portfolio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Buy Stock", new_your_stock_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Your Transaction", transactions_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/transactions/index.html.erb
<h1 class="text-center mt-3">Transaction List </h1>

<div class="container">
<table class="table mt-3">
<thead>
  <tr>
    <th scope="col"></th>
    <th scope="col">Symbol</th>
    <th scope="col">Buy Price</th>
    <th scope="col">Quantity</th>
    <th scope="col">Date</th>
    <th scope="col">Total Investment</th>
  </tr>
</thead>
<tbody>
  <% @transactions.each do |t|%>
  <tr>
    <td></td>
    <td class="text-uppercase"><%= t.your_stock.stock_symbol %></td>
    <td><%= t.your_stock.buy_price %></td>
    <td><%=t.your_stock.quatity %></td>
    <td><%=t.created_at %></td>
    <td><%= t.amount %></td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

app/views/your_stocks/new.html.erb
<h1 class="text-center"> Add Your Stock </h1> 

<div class="container mt-3">
  <%= form_for @your_stocks do |f| %>

    <div class="mb-3">
      <%= f.label 'Stock Symbol', class: "form-label" %>
      <%= f.text_field :stock_symbol, class: "form-control" %>
      <br /> <br />
    </div>

    <div class="mb-3">
      <%= f.label 'Buy Price', class: "form-label" %>
      <%= f.text_field :buy_price, class: "form-control" %>
      <br /> <br />
    </div>

    <div class="mb-3">
      <%= f.label 'Quantity', class: "form-label" %>
      <%= f.text_field :quatity, class: "form-control" %>
      <br /> <br />
    </div>

    <small>Enter range to sell or buy </small>
    <div class="mb-3">
      <%= f.label 'Sell Side Price', class: "form-label" %>
      <%= f.text_field :up_price, class: "form-control" %>
      <br /> <br />
    </div>

    <div class="mb-3">
      <%= f.label 'Buy Side Price', class: "form-label" %>
      <%= f.text_field :down_price, class: "form-control" %>
      <br /> <br />
    </div>

    <%= submit_tag "Add Stock" %>

  <% end %>
</div>